#language: bash
sudo: true
dist: xenial
language: node_js
node_js: '10'
services:
  - docker

cache:
  directories:
    - ~/.npm
    - ~/.rustup
    - ~/.cargo
    # cache built artifacts from install phase to speedup e2e
    - build 
    - artifacts
 
env:
  global:
    # runtime versions
    - RUST_VERSION=1.32.0
    - RUST_TARGETS=wasm32-unknown-unknown
    # browser versions
    - FIREFOX_VERSION=67.0b9
    - CHROME_VERSION=google-chrome-stable
    - BRAVE_CHROMEDRIVER_VERSION=2.33
    # Xorg config
    - SCREEN_RESOLUTION=1280x1024x24
    # misc
    - GITHUB_USERNAME=rnd-at-emurgo
    - GITHUB_EMAIL=rnd@emurgo.io
    - GIT_SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
    - CHROME_CODEBASE_URL=https://www.sample.com/dw/yoroi-extension.crx
    - CHROME_WEBSTORE_API_ENDPOINT=https://www.googleapis.com/upload/chromewebstore/v1.1
    - CHROME_DEV_APP_ID=febkioblpijdgicianpklkmolpbagnbo
    - CHROME_STG_APP_ID=bbaanljemfingpglehbbpdlhhahliihe
    - CHROME_PRO_APP_ID=fkkmcnnpaaimcaikbjgklcibgncdgejc
    - DISPLAY=:0

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- ${DISPLAY} -ac -screen 0 ${SCREEN_RESOLUTION}"
  - bash .travis/before_install.sh

install: 
  - npm ci

stages:
  - code-qa
  - build-yoroi
  - e2e-tests
  - deploy-artifacts
#  - build-docker

matrix:
  fast_finish: true
  include:

    # stage: code-qa
    - stage: code-qa
      name: "flow checks"
      script: npm run flow
    - stage: code-qa
      name: "eslint checks"
      script: npm run eslint
    - stage: code-qa
      name: "jest checks"
      script: npm run jest

    # stage: build-yoroi
    # 3x env in order to satisfy (build|artifacts) cache for e2e-tests
    - stage: build-yoroi
      #if: branch = master
      name: "build Yoroi extension"
      env:
        - BROWSER=chrome
        - BROWSER=firefox
        - BROWSER=brave
      script: bash .travis/build_yoroi.sh

    # stage: e2e-tests
    # NOTE: 3x $BROWSER is a hack to share cache from build-yoroi stage. Last env var prevails.
    - stage: e2e-tests
      name: "Brave End-to-End tests"
      if: branch = master
      env: 
        - BROWSER=chrome
        - BROWSER=firefox
        - BROWSER=brave
      install: bash .travis/e2e_tests_install.sh
      script: bash .travis/e2e_tests.sh
    - stage: e2e-tests
      if: branch =~ ^develop|staging|master OR type = pull_request
      name: "Chrome End-to-End tests"
      env:
        - BROWSER=firefox
        - BROWSER=brave
        - BROWSER=chrome
      install: bash .travis/e2e_tests_install.sh
      script: bash .travis/e2e_tests.sh
    - stage: e2e-tests
      if: branch =~ ^develop|staging|master OR type = pull_request
      name: "Firefox End-to-End tests"
      env:
        - BROWSER=brave
        - BROWSER=chrome
        - BROWSER=firefox
      install: bash .travis/e2e_tests_install.sh
      script: bash .travis/e2e_tests.sh

    - stage: artifacts-deploy
      name: "Upload artifacts to GH releases and extension stores"
      script: bash .travis/chrome_webstore_deploy.sh
      if: branch =~ ^develop|staging|master OR type = pull_request
      # env provides cache
      env:
        - BROWSER=brave
        - BROWSER=chrome
        - BROWSER=firefox

    #- stage: build-docker
    #  script: false

  allow_failures:
    - stage: build-docker

#before_deploy:
#  - git config --local user.name "${GITHUB_USERNAME}";
#  - git config --local user.email "${GITHUB_EMAIL}";
#  - export RELEASE_TAG="$(echo ${TRAVIS_BRANCH} | sed 's|/|-|g')-${GIT_SHORT_COMMIT}"
#  - git tag $RELEASE_TAG;

deploy:
  - provider: releases
    api_key:
      secure: j8A5oEK6c/jiD/AcwNbFaRJ6vXiNOGrqGDPfgQ2g5RDcTmSu5PA4SgHN2hTYjqSYt78zdBmOtfNY77rN9jy5R2iqGbqByT5Dd1fjO9CS9tIcKj/8+J8vMOK/scCimp2mVYxg84VXanPYctvMB/3AFi2bZNyNP85uXOAuxTFQ7h8KdCiJJC9JQkusSqTq82CmIqrzOZZ2TmqUhMS2skS9ZaRhUPW5jgutVFp38PQnqTeF40+jsKYhMgviuS/aBQF51TZbmNuLfUad0nNnKuWUiZDAvShdSgHZE8SAXaKvME5MR/BpeOQMHnE5ZCOxbiwjIi/QHgU0w+DSamNpEL1o3pm+sf7cexMIk0b18o1pBT8xCgFvVMRuIeN1Jy5JvXACP87k32P+J9HP9165cpdXORynqvwwpiuOPCXyxktGuZObR31Awq+MxNYrz5boTFcbA/eRxQKCEt4s2odzVmd/iRxaTJdO+Zs+DI2kw4TiFPZtYH66v6xitrTSHWBWsd2fEGlYXfGVDl2nhi6y+T09dJ0UEd/nS4UJvdfa8c7AeYUzw4EDOyawArTEIZsRrmq4Bspl61LcUZK/VJdxO3ZX0PyxbiZDXuH1ivmfB7jT2Ibl74Ui+LEk4yoBdVGliulwMMwDlYXxgCO/tqeIF/Q1r4oY9aT3tuoV+j9WwQ4brZ8=
    file_glob: true
    file:
      - artifacts/yoroi*zip
      - artifacts/yoroi*xpi
      - artifacts/yoroi*crx
      - artifacts/build*.tar.gz
      - artifacts/sha256sum.list
    overwrite: true
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      condition: ( $TRAVIS_BRANCH =~ staging|master ) && ( $TRAVIS_BUILD_STAGE_NAME = Artifacts-deploy )

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      # notify rcmorano
      - secure: uLazaQzraN0KlITJo3LiZ+eNP8UPuoLrtk2m7KWQPaqx2pUlBwAQKh7aSVj+QfnXUa4nQ6Q4HPq2P6j08GhD4b5vGjs7bmPk8ro2mnX/ECfgqfuon1CpvvD856DRJB1NlzI0BTlZlTLZ24TfvYFBB4CF5rh+Fe0DESNqqpwbLwOzQMms21I8VM/oFxOx+d4Uu7/rthIk0juxjS1DPLm+Owk761+MzQRq0XQYpsZpvE2w7ESJzpMjp8qTFKbNwJXbiel0ITNRzhzGVVKTNCNPnnbFSy2Ol6/6aLetLOnMQI1S+VZhUifigvcA9Pov9V6BHYk9+mCrsK93XavTwxSYUNenIf2zmIxkHzz0+EV9DXCysFNyxNq8QqOfwfDLHsfnKd2OsbJ/T5XuciHdizK04Fbp4hUl7HewUn7ywm0p8d+27Ddlrbxy5fdTOu+2YvivOpN5le200Xyhoa8u7fP9AhiRDdPCfor8KCbDRDjmZXTPlJFB8FoSs7bAOUQRuTvZqkI7E0BYrXEbGBwL3WANEb0HFECxg22Nxgx5wV4/owyX+iKN2MXLjKQnSUYCUhbu1xPhztd6jScMoNY0yirKVVbn3z6uuOJs3sk+MM5BrPY1PLtDj8cMqYHAGjsgvSRLFsKkwRQsmulrSyJAVY9z8AVmv3CSf6X9LQVCJKjY8SY=
