#language: bash
sudo: true
dist: xenial
language: node_js
node_js: '10'
services:
  - docker

cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/.cargo # cache cargo's cache
 
env:
  - BROWSER=chrome
  - BROWSER=brave
  - BROWSER=firefox
  global:
    - RUST_VERSION=1.32.0
    - CARDANO_NETWORK=mainnet   
    - E2E_BRAVE_DOCKER_IMAGE=rcmorano/circleci-node-8-browsers:brave
    - E2E_CHROME_DOCKER_IMAGE=circleci/node:8-browsers
    - E2E_FIREFOX_DOCKER_IMAGE=rcmorano/circleci-node-8-browsers:firefox-nightly
    - GIT_SHORT_COMMIT=${TRAVIS_COMMIT:0:7}

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - >
    if [ ! -e "$HOME/.cargo/bin" ];
    then
      curl https://sh.rustup.rs -sSf | sh -s -- -y;
      rustup install ${RUST_VERSION};
      rustup target add wasm32-unknown-unknown --toolchain ${RUST_VERSION}
    fi;
    sudo ln -s $HOME/.cargo/bin/* /usr/local/bin/;

script: 
  - npm ci
  # code quality checks
  - npm run flow
  - npm run eslint
  # javascript tests
  - npm run jest
  # create extensions to be consumed by browsers
  - npm run test-prepare

jobs:
  include:
    - stage: e2e-tests
      script: 
        - DOCKER_IMAGE=E2E_${BROWSER}_DOCKER_IMAGE;
        - docker run -it -v ${PWD}:/src -w /src --entrypoint=bash ${!DOCKER_IMAGE} -c "npm run test-e2e-${BROWSER}"
          
notifications:
  slack:
    on_success: change
    on_failure: always
    # notify rcmorano
    secure: kHi8Xliok2qLhuSIZDIGHUfe8EEGFGyfHViBQP40zK7arvI/8kY5h1OtBVP/s/BE3DRdzlM9IJ7R+B7dM8wuKpWflEB9mkamy0wTvEnIS4gIEGd50kDt0bcTxcEgPfJM4IVPwwEQrhd+ftX6YJ4bEQJioDWz+GGCtJXCFtmTj+mvMiySUpKKckwJj2tPQmnS/dCPpgcjLe/GSD3dCpsFvx1jfT3OJkJjkAdmUQlcHsFEtzWgcdgIPUX6OtB75zO1BJyutvTZ04bkQCcO5pZzOjd99BPmF2wqaS/ukD2KcMWUadcpSdi0CGxUN5FH02JlmJd6C6Im03I4SKYE+PKE1EUstx+DQaQ2sKvhKoN2fmK0SgLt2V6X4vlG3c/ofWT/nH6HljayHpetdnNgGIk66Ry7BApIs7oj53Cqe0q8vwN6vHwFHetcPWNHi0B48BYMcaAyNLNQCYEa6QEmiLibWiWWMFRpM1SJTrOow78CSitfK6hsGpbFjoGd0gGXwLbhQFvOzWg7IbJ4dNwi7S21Tat4qBs//j5DT9QrofvRPh83HnLs6W3IRJpuGFfxHp5DRGCigB7VQlgEHZED010gbuBa7i5JMSCy0vyn13uX5HJ6xYDXGT0W8NFY3/pIATiQCD8hP1JzhgRjQxa4JeCsZH5gu7gKXwDkQcwF7ehL+jM=
