# Javascript Node CircleCI 1.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

aliases:
  - &attach_workspace
      attach_workspace:
        at: ~/repo
  - &restore_cache
      restore_cache:
        keys:
          - generic-tools-cache-{{ checksum "package.json" }}
  - &save_cache
      save_cache:
        paths:
         - ~/.npm
         - ~/.rustup
         - ~/.cargo
        key: generic-tools-cache-{{ checksum "package.json" }}
  - &global_environment
      # runtime versions
      RUST_VERSION: 1.32.0
      RUST_TARGETS: wasm32-unknown-unknown
      # misc
      GITHUB_USERNAME: rnd-at-emurgo
      GITHUB_EMAIL: rnd@emurgo.io
      GIT_SHORT_COMMIT: ${CIRCLE_SHA1:0:7}
      CHROME_CODEBASE_URL: https://www.sample.com/dw/yoroi-extension.crx
      CHROME_WEBSTORE_API_ENDPOINT: https://www.googleapis.com/upload/chromewebstore/v1.1
      CHROME_DEV_APP_ID: febkioblpijdgicianpklkmolpbagnbo
      CHROME_STG_APP_ID: bbaanljemfingpglehbbpdlhhahliihe
      CHROME_PRO_APP_ID: fkkmcnnpaaimcaikbjgklcibgncdgejc
      SCREENSHOT_DIFF_THRESHOLD: 0
      SCREENSHOT_DIFF_COLOR: yellow

      # Encrypted env vars from ui:
      # AWS_ACCESS_KEY_ID: "${ARTIFACTS_KEY}"
      # AWS_SECRET_ACCESS_KEY: "${ARTIFACTS_SECRET}"
      # AWS_REGION: "${ARTIFACTS_REGION}"
      # S3_BUCKET: "${ARTIFACTS_BUCKET}"
      # DOCKER_USERNAME
      # DOCKER_PASSWORD
      # GITHUB_PAT
      # GOOGLE_CLIENT_ID
      # GOOGLE_CLIENT_SECRET
      # GOOGLE_REFRESH_TOKEN

checkout:
  # borrowed from: https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/8
  post:
    - |
        CIRCLE_PR_BASE_BRANCH=$(curl -su $GITHUB_USERNAME:$GITHUB_PAT | jq -r .base.ref)
        if [[ -n "${CIRCLE_PR_NUMBER}" ]]
        then
            # Update PR refs for testing.
            FETCH_REFS="+${CIRCLE_PR_BASE_BRANCH}:${CIRCLE_PR_BASE_BRANCH}"
            FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/head:pr/${CIRCLE_PR_NUMBER}/head"
            FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"

            # Retrieve the refs
            git fetch -u origin ${FETCH_REFS}

            # Checkout PR merge ref.
            git checkout -qf "pr/${CIRCLE_PR_NUMBER}/merge"

            # Test for merge conflicts.
            git branch --merged | grep ${CIRCLE_PR_BASE_BRANCH} > /dev/null
            git branch --merged | grep "pr/${CIRCLE_PR_NUMBER}/head" > /dev/null
        fi

jobs:
  build-setup:
    environment:
      <<: *global_environment
      POC: poc
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout
      - run: bash .circleci/stop_redundant_jobs.sh
      - *restore_cache
      - run: bash .circleci/before_install.sh

      - run: npm ci
      - *save_cache
      
      # code quality checks
      - run: npm run flow
      - run: npm run eslint

      # run jest tests
      - run: npm run jest

      # create extensions to be consumed by browsers
      - run: bash .circleci/build_yoroi.sh

      # persist results to then use them in tests
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-brave:
    environment:
      <<: *global_environment
      BROWSER: brave
    working_directory: ~/repo
    docker:
      - image: emurgornd/circleci-node-8-browsers:brave

    steps:
      - *attach_workspace
      - *restore_cache
      - run: bash .circleci/e2e_tests.sh
      - run: bash .circleci/s3_screenshots_upload.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-chrome:
    environment:
      <<: *global_environment
      BROWSER: chrome
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers

    steps:
      - *attach_workspace
      - *restore_cache
      - run: bash .circleci/e2e_tests.sh
      - run: bash .circleci/s3_screenshots_upload.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-firefox:
    environment:
      <<: *global_environment
      BROWSER: firefox
    working_directory: ~/repo
    docker:
      # unsiggned addons are only supported in Firefox-dev, Firefox nightly and Firefox-esr
      # CircleCI comes w/ Firefox but we need to replace it w/ Firefox-esr,
      # so we use a custom image derivated from circleci's one:
      - image: emurgornd/circleci-node-8-browsers:firefox-dev

    steps:
      - *attach_workspace
      - *restore_cache
      - run: bash .circleci/e2e_tests.sh
      - run: bash .circleci/s3_screenshots_upload.sh

  deploy-artifacts:
    environment:
      <<: *global_environment
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers

    steps:
      - *attach_workspace
      - run: bash .circleci/chrome_webstore_deploy.sh
      - run: bash .circleci/s3_artifacts_upload.sh
      - run: bash .circleci/pull_request_comment.sh

  ondemand-build:
    environment:
      <<: *global_environment
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers
    steps:
      - *attach_workspace
      - run: echo $RUN_EXTRA_TESTS

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-setup:
          context: yoroi-frontend
      - test-brave:
          context: yoroi-frontend
          filters:
            branches:
              only:
                - master
          requires:
            - build-setup
      - test-chrome:
          context: yoroi-frontend
          filters:
            branches:
              ignore:
                - l10n_develop
          requires:
            - build-setup
      - test-firefox:
          context: yoroi-frontend
          filters:
            branches:
              ignore:
                - l10n_develop
          requires:
            - build-setup
      - deploy-artifacts:
          context: yoroi-frontend
          requires:
            - test-chrome
            - test-firefox
      - ondemand-build:
          filters:
            branches:
              ignore: /.*/
